In [1]:
from bs4 import BeautifulSoup

In [2]:
with open("beautifulsoup_practice.html","r") as f:
    html = f.read()

In [3]:
soup = BeautifulSoup(html,"html.parser")
soup

<!DOCTYPE html>

<html>
<head>
<title>BeautifulSoup Practice Website</title>
</head>
<body>
<h1 id="main-title">LJU Student Portal</h1>
<div class="student" data-id="101">
<h2 class="name">Dhruv Patel</h2>
<p class="department">Computer Engineering</p>
<p class="email">
            Email:
            <span>dhruv@gmail.com</span>
</p>
<a href="https://linkedin.com/dhruv">
            LinkedIn Profile
        </a>
<img alt="Dhruv Image" src="dhruv.jpg"/>
</div>
<div class="student" data-id="102">
<h2 class="name">Riya Shah</h2>
<p class="department">IT Engineering</p>
<p class="email">
            Email:
            <span>riya@gmail.com</span>
</p>
<a href="https://linkedin.com/riya">
            LinkedIn Profile
        </a>
<img alt="Riya Image" src="riya.jpg"/>
</div>
<div class="student" data-id="103">
<h2 class="name">Amit Joshi</h2>
<p class="department">AI &amp; DS</p>
<p class="email">
            Email:
            <span>amit@gmail.com</span>
</p>
<a href="https://linkedin.com/amit">
            LinkedIn Profile
        </a>
<img alt="Amit Image" src="amit.jpg"/>
</div>
<hr/>
<h2>Student Marks Table</h2>
<table border="1" id="marks-table">
<tr>
<th>ID</th>
<th>Name</th>
<th>Python</th>
<th>Django</th>
</tr>
<tr>
<td>101</td>
<td>Dhruv</td>
<td>95</td>
<td>90</td>
</tr>
<tr>
<td>102</td>
<td>Riya</td>
<td>88</td>
<td>91</td>
</tr>
<tr>
<td>103</td>
<td>Amit</td>
<td>92</td>
<td>85</td>
</tr>
</table>
</body>
</html>

In [5]:
soup.h1

In [4]:
z = soup.find("title").text
print(z)

BeautifulSoup Practice Website

In [6]:
soup.find("p",class_="email").text.strip()

'Email:\n            dhruv@gmail.com'

In [7]:
soup.find("p").text

'Computer Engineering'

In [8]:
em = soup.find("span").text
em

'dhruv@gmail.com'

In [14]:
so = soup.find("a").text.strip()
so

'LinkedIn Profile'

In [18]:
name = soup.find("h2").text
name

'Dhruv Patel'

In [22]:
dept = soup.find("p",{"class":"department"}).text
dept

'Computer Engineering'

In [24]:
import pandas as pd
data = {"Student Name":name,"Department":dept,"Email":em,"Social Media":so}   #must pass in list
df = pd.DataFrame(data)
df

ValueError: If using all scalar values, you must pass an index

In [23]:
import pandas as pd
data = {"Student Name":[name],"Department":[dept],"Email":[em],"Social Media":[so]}
df = pd.DataFrame(data)
df

  Student Name            Department            Email      Social Media
0  Dhruv Patel  Computer Engineering  dhruv@gmail.com  LinkedIn Profile

# find_all

In [25]:
soup.find("h2")

In [28]:
z = soup.find_all("h2") #list

In [29]:
for i in z:
    print(i.text)

Dhruv Patel
Riya Shah
Amit Joshi
Student Marks Table

In [46]:
z = soup.find_all("div",{"class":"student"})
n = []
d = []
e = []
a = []
i1 = []
for i in z:
    name = i.find("h2").text
    n.append(name)
    dept = i.find("p",{"class":"department"}).text
    d.append(dept)
    email = i.find("span").text
    e.append(email)
    link = i.find("a")
    a.append(link["href"])
    img = i.find("img")
    i1.append(img["alt"])

In [47]:
data = {"Name":n,"Department":d,"Email":e,"Link":a,"Image":i1}
df = pd.DataFrame(data)
df

,Name,Department,Email,Link,Image
0,Dhruv Patel,Computer Engineering,dhruv@gmail.com,https://linkedin.com/dhruv,Dhruv Image
1,Riya Shah,IT Engineering,riya@gmail.com,https://linkedin.com/riya,Riya Image
2,Amit Joshi,AI & DS,amit@gmail.com,https://linkedin.com/amit,Amit Image

In [48]:
z = soup.find_all("div",{"class":"student"},limit=2)
n = []
d = []
e = []
a = []
i1 = []
for i in z:
    name = i.find("h2").text
    n.append(name)
    dept = i.find("p",{"class":"department"}).text
    d.append(dept)
    email = i.find("span").text
    e.append(email)
    link = i.find("a")
    a.append(link["href"])
    img = i.find("img")
    i1.append(img["alt"])

In [49]:
data = {"Name":n,"Department":d,"Email":e,"Link":a,"Image":i1}
df = pd.DataFrame(data)
df

,Name,Department,Email,Link,Image
0,Dhruv Patel,Computer Engineering,dhruv@gmail.com,https://linkedin.com/dhruv,Dhruv Image
1,Riya Shah,IT Engineering,riya@gmail.com,https://linkedin.com/riya,Riya Image

In [69]:
z = soup.find_all("div",{"class":"student"})[0:2]
n = []
d = []
e = []
a = []
i1 = []
e1 = []
a1 = []
for i in z:
    name = i.find("h2").text
    n.append(name)
    dept = i.find("p",{"class":"department"}).text
    d.append(dept)
    email = i.find("span").text.split("@")
    e.append(email[0])
    e1.append(email[1])
    link = i.find("a")
    a.append(link["href"])
    img = i.find("img")
    i1.append(img["alt"])

In [70]:
data = {"Name":n,"Department":d,"Email":e,"Link":a,"Image":i1,"Extenstion":e1,"Linkdin name":a1}
df = pd.DataFrame(data)
df

ValueError: All arrays must be of the same length

In [71]:
soup.find("h2",{"class":"name"},string="Riya Shah")

# Scraping from website

In [10]:
from bs4 import BeautifulSoup

In [11]:
url = "https://www.politifact.com/factchecks/list/"
import requests

In [12]:
data = requests.get(url)
html = data.text
data.status_code

ConnectionError: HTTPSConnectionPool(host='www.politifact.com', port=443): Max retries exceeded with url: /factchecks/list/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F4510E0050>: Failed to resolve 'www.politifact.com' ([Errno 11001] getaddrinfo failed)"))

In [16]:
soup = BeautifulSoup(html,"html.parser")

In [19]:

# x = soup.find_all("li",{"class":"o-listicle_item"})
# n = []
# d = []
# e = []
# author = []
# for i in x:
#     name = i.find("a",{"class":"m-statement__name"}).text.strip()
#     n.append(name)
#     date = i.find("div",class_ = "m-statement__desc").text.split()
#     d.append(date)
#     fo = i.find("footer",class_ = "m-statement__footer").text.split().split("•")
#     e.append(fo[1])
#     author.append(fo[0])
soup = BeautifulSoup(html,'html.parser')
x = soup.find_all('li',{'class':'o-listicle__item'})
n=[]
d=[]
e=[]
author=[]

for i in x:
    name = i.find('a',{'class':'m-statement__name'}).text.strip()
    n.append(name)
    date = i.find("div",{'class':"m-statement__desc"}).text.strip()
    d.append(date)
    fo = i.find('footer',{'class':'m-statement__footer'}).text.strip().split('•')
    e.append(fo[1])
    author.append(fo[0])

In [20]:
data = {"name":n,"date":d,"state":e,"at":author}
import pandas as pd
df = pd.DataFrame(data)
df

,name,date,state,at
0,X posts,"stated on May 14, 2026 in X posts:","May 15, 2026",By Loreben Tuquero
1,X posts,"stated on May 6, 2026 in an X post:","May 14, 2026",By Maria Briceño
2,Kathy Castor,"stated on April 29, 2026 in an X post:","May 14, 2026",By Samantha Putterman
3,Vivek Ramaswamy,"stated on April 24, 2026 in an ad:","May 13, 2026",By Amy Sherman
4,TikTok posts,"stated on May 8, 2026 in una publicación en Ti...","May 13, 2026",By Maria Briceño
5,Christine Quinn,"stated on March 5, 2026 in a press release:","May 11, 2026",By Andrew McGurl
6,Nicholas Langworthy,"stated on March 31, 2026 in an X post:","May 11, 2026",By Holden Turek
7,Donald Trump,"stated on May 7, 2026 in remarks to reporters:","May 8, 2026",By Louis Jacobson
8,Byron Donalds,"stated on May 4, 2026 in an interview:","May 8, 2026",By Samantha Putterman
9,Marcy Kaptur,"stated on May 5, 2026 in an X post:","May 8, 2026",By Maria Briceño
10,Liz Krueger,"stated on March 5, 2026 in an op-ed:","May 7, 2026",By Conor Amendola
11,X posts,"stated on May 6, 2026 in a social media post:","May 7, 2026",By Louis Jacobson
12,Donald Trump,"stated on May 4, 2026 in a White House event:","May 6, 2026",By Louis Jacobson
13,Sam Sutton,"stated on March 11, 2026 in a rally:","May 5, 2026",By Emma Gavazzi
14,Fentrice Driskell,"stated on April 29, 2026 in an interview:","May 1, 2026",By Samantha Putterman
15,Instagram posts,"stated on April 26, 2026 in una publicación en...","April 30, 2026",By Maria Briceño
16,Bernie Sanders,"stated on April 22, 2026 in a Senate committee...","April 30, 2026",By Amy Sherman
17,Tim Scott,"stated on April 26, 2026 in an X post:","April 29, 2026",By Louis Jacobson
18,Pine Tree Results PAC,"stated on April 26, 2026 in an ad:","April 29, 2026",By Amy Sherman
19,Social Media,"stated on April 26, 2026 in social media posts:","April 29, 2026",By Maria Briceño
20,Donald Trump,"stated on April 23, 2026 in remarks at the Whi...","April 29, 2026",By Louis Jacobson
21,Ron DeSantis,"stated on April 27, 2026 in an interview with ...","April 29, 2026",By Louis Jacobson
22,Social Media,"stated on April 26, 2026 in publicaciones en r...","April 28, 2026",By Maria Briceño
23,Jay Collins,"stated on April 20, 2026 in a campaign document:","April 23, 2026",By Samantha Putterman
24,Robert F. Kennedy Jr.,"stated on April 22, 2026 in testimony to the S...","April 23, 2026",By Louis Jacobson
25,Joe Rogan,"stated on April 18, 2026 in comments at the Ov...","April 22, 2026",By Grace Abels
26,X posts,"stated on April 21, 2026 in an X post:","April 22, 2026",By Maria Briceño
27,Chris Wright,"stated on April 19, 2026 in an interview on CN...","April 22, 2026",By Louis Jacobson
28,Facebook posts,"stated on April 19, 2026 in Facebook posts:","April 21, 2026",By Loreben Tuquero
29,Democratic National Committee,"stated on April 3, 2026 in a post on X:","April 20, 2026",By Zoe Weyand

In [11]:
n

[]

In [12]:
d

[]

In [23]:
html

'\n\n\n\n<!DOCTYPE html>\n<html lang="en-US" dir="ltr">\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="x-ua-compatible" content="ie=edge">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Fact-checks | PolitiFact </title>\n\n  <meta name="description" content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." />\n  <meta name="robots" content="all" />\n  <meta name="publisher" content="PolitiFact">\n  \n  \n  \n  \n  \n\n  \n  \n  \n\n  \n  \n  <meta name="twitter:username" content="PolitiFact"/>\n  \n  <meta name="twitter:card" content="summary" />\n  <meta name="twitter:site" content="PolitiFact">\n  <meta name="twitter:url" content="" />\n  <meta name="twitter:title" content="" />\n  <meta name="twitter:description" content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter."/>\n  \n  \n  \n  <meta name="facebook-domain-verification" content="vrxxsw8mwnf2pxgnwxvgsn4g93w3vm"/>\n  \n\n\n  <link rel="shortcut icon" type="image/ico" href="https://static.politifact.com/images/favicon.ico">\n  <link rel="icon" type="image/png" href="https://static.politifact.com/images/favicon.png">\n  <link rel="apple-touch-icon" href="https://static.politifact.com/images/apple-touch-icon.png">\n  \n  \n  <link rel="alternate" type="application/rss+xml" title="Latest Fact-checks and Articles" href="/rss/social/"/>\n  <link rel="alternate" type="application/rss+xml" title="Latest Fact-checks" href="/rss/factchecks/"/>\n  \n  \n\n  \n  <script src="https://static.politifact.com/js/sharethefacts-v1.js"></script>\n  \n<script type="text/javascript" src="//d283fm003ll1xs.cloudfront.net/script.js"></script>\n\n\n\n<script> !(function () { window.googletag = window.googletag || {}; window.vmpbjs = window.vmpbjs || {}; window.vpb = window.vpb || {}; vpb.cmd = vpb.cmd || []; vpb.st=Date.now();  vpb.fastLoad = true; googletag.cmd = googletag.cmd || []; vmpbjs.cmd = vmpbjs.cmd || []; var cmds = []; try{ cmds = googletag.cmd.slice(0); googletag.cmd.length = 0; }catch(e){} var ready = false; function exec(cb) { return cb.call(googletag); } var overriden = false; googletag.cmd.push(function () { overriden = true; googletag.cmd.unshift = function (cb) { if (ready) { return exec(cb); } cmds.unshift(cb); if (cb._startgpt) { ready = true; for (var k = 0; k < cmds.length; k++) { exec(cmds[k]); } } }; googletag.cmd.push = function (cb) { if (ready) { return exec(cb); } cmds.push(cb); }; }); if(!overriden){ googletag.cmd.push = function (cb) { cmds.push(cb); }; googletag.cmd.unshift = function (cb) { cmds.unshift(cb); if (cb._startgpt) { ready = true; if (googletag.apiReady) { cmds.forEach(function (cb) { googletag.cmd.push(cb); }); } else { googletag.cmd = cmds; } } }; } var dayMs = 36e5, cb = parseInt(Date.now() / dayMs), vpbSrc = \'//player.hbmp.ops.co/prebidlink/\' + cb + \'/wrapper_hb_779253_23204.js\', pbSrc = vpbSrc.replace(\'wrapper_hb\', \'hb\'), gptSrc = \'//securepubads.g.doubleclick.net/tag/js/gpt.js\', c = document.head || document.body || document.documentElement; function loadScript(src, cb) { var s = document.createElement(\'script\'); s.src = src; s.defer=false; c.appendChild(s); s.onload = cb; s.onerror = function(){ var fn = function(){}; fn._startgpt = true; googletag.cmd.unshift(fn); }; return s; } loadScript(pbSrc); loadScript(gptSrc); loadScript(vpbSrc); })() </script>\n\n\n<script>\n  window.googletag = window.googletag || {cmd: []};\n  googletag.cmd.push(function() {\n    const sizeMapping = googletag.sizeMapping()\n        .addSize([1440, 0], [\n            [970,90],\n            [970,250],\n            [728,90],\n        ])\n        .addSize([1024, 0], [\n            [728,90],\n            [320,100],\n        ])\n        .addSize([768, 0], [\n            [320, 50],\n            [300, 50],\n        ])\n        .addSize([0, 0], [\n            [320, 50],\n\t\t\t[300, 50],\n        ])\n        .build();\n    googletag.defineSlot(\'/25722649/Politifact/BottomLeaderboard_Adhesion\', [[300,50],[320,50],[728,90]], \'BottomLeaderboard_Adhesion\')\n      .defineSizeMapping(sizeMapping) \n      .addService(googletag.pubads());\n    googletag.defineSlot(\'/25722649/Politifact/Politifact_BottomLeaderboard\', [[320,50],[728,90]], \'BottomLeaderboard\')\n      .defineSizeMapping(sizeMapping)          \n      .addService(googletag.pubads());\n    googletag.defineSlot(\'/25722649/Politifact/Politifact_MiddleRectangle\', [[300,250]], \'MiddleRectangle\')\n             .addService(googletag.pubads());\n    googletag.defineSlot(\'/25722649/Politifact/Politifact_TopLeaderboard\', [[320,50],[728,90]], \'TopLeaderboard\')\n      .defineSizeMapping(sizeMapping)        \n      .addService(googletag.pubads());\n    googletag.defineSlot(\'/25722649/Politifact/Politifact_TopMedRect\', [[300,250],[300,600]], \'TopMedRect\')\n             .addService(googletag.pubads());\n    googletag.defineSlot(\'/25722649/Politifact/SmartNewsFeed\', [[300,250]], \'SmartNewsFeed\')\n             .addService(googletag.pubads());\n\n    googletag.pubads().enableSingleRequest();\n    googletag.enableServices();\n  });\n</script>\n\n\n  \n<script async src="https://www.googletagmanager.com/gtag/js?id=UA-35156640-2"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'UA-35156640-2\');\n  \n</script>\n\n\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-EDXB0TJGGY"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'G-EDXB0TJGGY\');\n  \n</script>\n\n\n<script async id="ebx" src="//applets.ebxcdn.com/ebx.js"></script>\n\n\n  <div id="fb-root"></div>\n  <script>(function(d, s, id) {\n    var js, fjs = d.getElementsByTagName(s)[0];\n    if (d.getElementById(id)) return;\n    js = d.createElement(s); js.id = id;\n    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";\n    fjs.parentNode.insertBefore(js, fjs);\n  }(document, \'script\', \'facebook-jssdk\'));</script>\n  <!-- End Facebook Pixel Code -->\n  <noscript><img height="1" width="1" style="display:none" src="//www.facebook.com/tr?id=292850974235854&ev=PageView&noscript=1"/></noscript>\n  <link rel="stylesheet" href="https://static.politifact.com/assets/main-CiDydm0l.css" />\n<style>\n.m-notfound{padding-top:2.5rem;padding-bottom:3.5rem}@media print, screen and (min-width: 48em){.m-notfound{padding-top:5rem;padding-bottom:6rem}}.m-notfound__title{margin-bottom:2.5rem;text-align:center}@media print, screen and (min-width: 48em){.m-notfound__content{display:-webkit-box;display:-ms-flexbox;display:flex}}.m-notfound__image{margin-bottom:1.5rem;margin-left:auto;margin-right:auto;max-width:10rem}@media print, screen and (min-width: 48em){.m-notfound__image{-webkit-box-flex:0;-ms-flex:0 0 13.75rem;flex:0 0 13.75rem;max-width:none}}.m-notfound__body{padding-top:.5rem}@media print, screen and (min-width: 48em){.m-notfound__body{padding-left:2rem}}.m-notfound__body p{margin-top:0}\n</style>\n\n\n</head>\n\n<body class="" data-role="page">\n  <div id="top" class="global-wrapper">\n    \n\n\n    <header class="o-header">\n      <div class="o-header__inner">\n        <div class="o-header__branding">\n          <a href="/">\n            <span class="m-branding">\n              <span class="m-branding__logo">\n                <svg class="c-icon ">\n                  <use xlink:href="#svg_logo-plain"></use>\n                </svg>\n              </span>\n              <span class="m-branding__subline">\n                <span class="m-branding__claim">\n                  The Poynter Institute\n                </span>\n              </span>\n            </span>\n          </a>\n        </div>\n        <div class="o-header__menu">\n          <a href="#" class="c-burger" data-menu-toggle>\n            <span class="c-burger__lines"></span>\n            <span class="c-burger__value">Menu</span>\n          </a>\n        </div>\n        <div class="o-header__donate">\n          <a class="c-button c-button--small show-for-large" href="/membership/">\n            Donate\n          </a>\n        </div>\n      </div>\n      <div class="t-menu" data-menu>\n        <div class="t-menu__content">\n          <div class="o-menu-list">\n            <div class="o-menu-list__inner">\n              <div class="o-menu-list__item">\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_1" name="" value="">\n                  <label for="togglist_1" class="m-togglist__label" aria-controls="togglist_1" aria-expanded="false" role="tab" aria-selected="true">\n                    State Editions\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_1" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <a href="/california/">\n                          California\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/florida/">\n                          Florida\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/iowa/">\n                          Iowa\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/michigan/">\n                          Michigan\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/new-hampshire/">\n                          New Hampshire\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/new-york/">\n                          New York\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/north-carolina/">\n                          North Carolina\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/pennsylvania/">\n                          Pennsylvania\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/texas/">\n                          Texas\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/west-virginia/">\n                          West Virginia\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/wisconsin/">\n                          Wisconsin\n                        </a>\n                      </li>\n                      <li>\n                    </ul>\n                  </div>\n                </div>\n              </div>\n              <div class="o-menu-list__item">\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_2" name="" value="">\n                  <label for="togglist_2" class="m-togglist__label" aria-controls="togglist_2" aria-expanded="false" role="tab" aria-selected="true">\n                    Issues\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_2" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <strong><a href="/issues/">All Issues</a></strong>\n                      </li>\n                      <li>\n                        <a href="/factchecks/list/?speaker_type=SOCIAL">\n                          Online hoaxes\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/coronavirus/">\n                          Coronavirus\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/health-check/">\n                          Health Care\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/immigration/">\n                          Immigration\n                        </a>\n                      </li>\n                      <li>\n                        <a href="https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/">\n                          Extremism\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/taxes/">\n                          Taxes\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/marijuana/">\n                          Marijuana\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/environment/">\n                          Environment\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/crime/">\n                          Crime\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/guns/">\n                          Guns\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/foreign-policy/">\n                          Foreign Policy\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/lgbtq/">\n                          LGBTQ+\n                        </a>\n                      </li>\n                    </ul>\n                  </div>\n                </div>\n              </div>\n\n              <div class="o-menu-list__item">\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_3" name="" value="">\n                  <label for="togglist_3" class="m-togglist__label" aria-controls="togglist_3" aria-expanded="false" role="tab" aria-selected="true">\n                    People\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_3" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <a href="/personalities/donald-trump/">\n                          Donald Trump\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/jd-vance/">\n                          JD Vance\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/mitch-mcconnell/">\n                          Mitch McConnell\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/mike-johnson/">\n                          Mike Johnson\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/joe-biden/">\n                          Joe Biden\n                        </a>\n                      </li>\n                    </ul>\n                  </div>\n                </div>\n              </div>\n              <div class="o-menu-list__item">\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_4" name="" value="">\n                  <label for="togglist_4" class="m-togglist__label" aria-controls="togglist_4" aria-expanded="false" role="tab" aria-selected="true">\n                    Media\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_4" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <a href="/punditfact/">\n                          PunditFact\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/tucker-carlson/">\n                          Tucker Carlson\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/sean-hannity/">\n                          Sean Hannity\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/rachel-maddow/">\n                          Rachel Maddow\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/personalities/blog-posting/">\n                          Bloggers\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/videos/">\n                          PolitiFact Videos\n                        </a>\n                      </li>\n                    </ul>\n                  </div>\n                </div>\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_5" name="" value="">\n                  <label for="togglist_5" class="m-togglist__label" aria-controls="togglist_5" aria-expanded="false" role="tab" aria-selected="true">\n                    Campaigns\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_5" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <a href="/elections/">\n                          2024 Elections\n                        </a>\n                      </li>\n                    </ul>\n                  </div>\n                </div>\n              </div>\n              <div class="o-menu-list__item">\n                <div class="m-togglist" role="tablist" aria-multiselectable="true">\n                  <input class="m-togglist__checkbox show-for-sr" type="checkbox" id="togglist_6" name="" value="">\n                  <label for="togglist_6" class="m-togglist__label" aria-controls="togglist_6" aria-expanded="false" role="tab" aria-selected="true">\n                    Truth-o-Meter\n                  </label>\n                  <div class="m-togglist__panel" aria-labelledby="togglist_6" role="tabpanel" aria-hidden="true">\n                    <ul class="m-togglist__list">\n                      <li>\n                        <a href="/factchecks/list/?ruling=true">\n                          True\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/factchecks/list/?ruling=mostly-true">\n                          Mostly True\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/factchecks/list/?ruling=half-true">\n                          Half True\n                        </a>\n                      </li>\n                      <li>\n                        <a href="/factchecks/list/?ruling=barely-true">\n                          Mostly False\n                        </a>\n                      </li>\n     

# Flipkart question

In [21]:
with open("flipkart.html","r",encoding="utf-8") as f:
    html = f.read()

In [22]:
soup = BeautifulSoup(html,"html.parser")

In [76]:
z = soup.find_all("div",class_="_3pLy-c row")
n = []
r = []
b = []
p = []
d = []
dp = []
pn = []
co = []
st = [] 
for i in z:
    name = i.find("div",class_="_4rR01T").text.strip()
    n.append(name)
    rate = i.find("div",class_="_3LWZlK").text.strip()
    r.append(rate)
    battery = i.find_all("li",class_="rgWa7D")[3]
    b.append(battery.text)
    price = i.find("div",class_="_30jeq3 _1_WHN1").text.strip()
    p.append(price)
    discount = i.find("div",class_="_3Ay6Sb")
    if discount:
        d.append(discount.text.strip())
    else:
        d.append("None")
    d_price = i.find("div",class_="_3I9_wc _27UcVY")
    if d_price:
        dp.append(d_price.text.strip())
    else:
        dp.append("None")


for i in n:
    x = i.split('(')
    pn.append(x[0])
    co.append((i.split("("))[1].split(",")[0])

In [77]:
co

['Mystic Silver',
 'Prestige Gold',
 'Phantom Black',
 'Phantom Black',
 'Interstellar Black',
 'Starlight White',
 'Awesome Violet',
 'Glacial Green',
 'Green',
 'Interstellar Glow',
 'Cosmic Black',
 'Cream',
 'Cosmic Black',
 'Aurora Dawn',
 'Hacker Black',
 'Nano Silver',
 'Winter Mist',
 'Red',
 'Astral Black',
 'Opera Mauve',
 'Couture Blue',
 'Steel Black',
 'Aurora Dawn',
 'Couture Blue']

In [78]:
data = {"Name":n,"Phone_Name":pn,"Color":co,"Storage":,"Rating":r,"Battery":b,"Price":p,"Discount":d,"Discount_Price":dp}
df = pd.DataFrame(data)
df

,Name,Phone_Name,Color,Rating,Battery,Price,Discount,Discount_Price
0,"Huawei P9 (Mystic Silver, 32 GB)",Huawei P9,Mystic Silver,4.5,3000 mAh Battery,"₹39,999",2% off,"₹40,999"
1,"Huawei P9 (Prestige Gold, 32 GB)",Huawei P9,Prestige Gold,4.5,3000 mAh Battery,"₹39,999",2% off,"₹40,999"
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",SAMSUNG Galaxy S22 Plus 5G,Phantom Black,4.5,4500 mAh Lithium-ion Battery,"₹49,999",50% off,"₹1,01,999"
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",SAMSUNG Galaxy Z Flip3 5G,Phantom Black,4.3,3300 mAh Lithium-ion Battery,"₹44,999",53% off,"₹95,999"
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",MOTOROLA Edge 30 Ultra,Interstellar Black,4.2,4610 mAh Lithium Battery,"₹49,999",33% off,"₹74,999"
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",MOTOROLA Edge 30 Ultra,Starlight White,4.2,4610 mAh Lithium Battery,"₹49,999",33% off,"₹74,999"
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",SAMSUNG Galaxy A54 5G,Awesome Violet,4.3,5000 mAh Battery,"₹40,999",10% off,"₹45,999"
7,"OnePlus 8 (Glacial Green, 256 GB)",OnePlus 8,Glacial Green,4.5,4300 mAh Battery,"₹46,999",2% off,"₹47,999"
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",SAMSUNG Galaxy S22 Plus 5G,Green,4.5,4500 mAh Lithium-ion Battery,"₹49,999",50% off,"₹1,01,999"
9,"OnePlus 8 (Interstellar Glow, 256 GB)",OnePlus 8,Interstellar Glow,4.5,4300 mAh Battery,"₹47,349",1% off,"₹47,999"
10,"Mi 10T Pro (Cosmic Black, 128 GB)",Mi 10T Pro,Cosmic Black,4.2,5000 mAh Li-ion Polymer Battery,"₹38,849",19% off,"₹47,999"
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",SAMSUNG Galaxy Z Flip3 5G,Cream,4.3,3300 mAh Lithium-ion Battery,"₹44,999",53% off,"₹95,999"
12,"vivo X70 Pro (Cosmic Black, 256 GB)",vivo X70 Pro,Cosmic Black,4.4,4450 mAh Battery,"₹49,999",13% off,"₹57,990"
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",vivo X70 Pro,Aurora Dawn,4.4,4450 mAh Battery,"₹47,999",17% off,"₹57,990"
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",OnePlus 9RT 5G,Hacker Black,4.1,4500 mAh Battery,"₹48,999",None,None
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",OnePlus 9RT 5G,Nano Silver,4.1,4500 mAh Battery,"₹46,999",None,None
16,"OnePlus 9 5G (Winter Mist, 256 GB)",OnePlus 9 5G,Winter Mist,4,4500 mAh Battery,"₹49,999",None,None
17,"APPLE iPhone 11 (Red, 128 GB)",APPLE iPhone 11,Red,4.6,A13 Bionic Chip Processor,"₹46,999",3% off,"₹48,900"
18,"OnePlus 9 5G (Astral Black, 128 GB)",OnePlus 9 5G,Astral Black,3.9,4500 mAh Battery,"₹49,999",None,None
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",Xiaomi 12 Pro 5G,Opera Mauve,4.2,4600 mAh Lithium Polymer Battery,"₹43,990",45% off,"₹79,990"
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",Xiaomi 12 Pro 5G,Couture Blue,4.2,4600 mAh Lithium Polymer Battery,"₹43,900",45% off,"₹79,990"
21,"realme GT 2 Pro (Steel Black, 128 GB)",realme GT 2 Pro,Steel Black,4.2,5000 mAh Lithium Ion Battery,"₹49,999",13% off,"₹57,999"
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",vivo X70 Pro,Aurora Dawn,4.5,4450 mAh Battery,"₹48,999",10% off,"₹54,990"
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",Xiaomi 12 Pro 5G,Couture Blue,4.1,4600 mAh Lithium Polymer Battery,"₹48,880",42% off,"₹84,999"

In [50]:
b

['3000 mAh Battery',
 '3000 mAh Battery',
 '4500 mAh Lithium-ion Battery',
 '3300 mAh Lithium-ion Battery',
 '4610 mAh Lithium Battery',
 '4610 mAh Lithium Battery',
 '5000 mAh Battery',
 '4300 mAh Battery',
 '4500 mAh Lithium-ion Battery',
 '4300 mAh Battery',
 '5000 mAh Li-ion Polymer Battery',
 '3300 mAh Lithium-ion Battery',
 '4450 mAh Battery',
 '4450 mAh Battery',
 '4500 mAh Battery',
 '4500 mAh Battery',
 '4500 mAh Battery',
 'A13 Bionic Chip Processor',
 '4500 mAh Battery',
 '4600 mAh Lithium Polymer Battery',
 '4600 mAh Lithium Polymer Battery',
 '5000 mAh Lithium Ion Battery',
 '4450 mAh Battery',
 '4600 mAh Lithium Polymer Battery']

In [ ]:
z = soup.find_all("div",{"class":"student"})
n = []
d = []
e = []
a = []
i1 = []
for i in z:
    name = i.find("h2").text
    n.append(name)
    dept = i.find("p",{"class":"department"}).text
    d.append(dept)
    email = i.find("span").text
    e.append(email)
    link = i.find("a")
    a.append(link["href"])
    img = i.find("img")
    i1.append(img["alt"])

# API

In [3]:
import requests

In [8]:
lat = 23.033863
lon = 72.585022
api_key = "13041aa49ecf4721a622bb9380221192"
url = f"https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={api_key}"
data = requests.get(url)
new = data.json()

In [9]:
new

{'cod': 401,
 'message': 'Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.'}

In [22]:
import requests

lat = 23.033863
lon = 72.585022

API_key = "afc717f99a9037f35ac78572f44a98f6"

url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_key}"

data = requests.get(url)

data.status_code

200

In [23]:
new=data.json()
new

{'coord': {'lon': 72.5873, 'lat': 23.0258},
 'weather': [{'id': 711,
   'main': 'Smoke',
   'description': 'smoke',
   'icon': '50d'}],
 'base': 'stations',
 'main': {'temp': 304.16,
  'feels_like': 304.86,
  'temp_min': 304.16,
  'temp_max': 304.16,
  'pressure': 1010,
  'humidity': 45,
  'sea_level': 1010,
  'grnd_level': 1004},
 'visibility': 3000,
 'wind': {'speed': 2.06, 'deg': 260},
 'clouds': {'all': 0},
 'dt': 1779422652,
 'sys': {'type': 1,
  'id': 9049,
  'country': 'IN',
  'sunrise': 1779409578,
  'sunset': 1779457595},
 'timezone': 19800,
 'id': 1279233,
 'name': 'Ahmedabad',
 'cod': 200}

In [24]:
new["main"]

{'temp': 304.16,
 'feels_like': 304.86,
 'temp_min': 304.16,
 'temp_max': 304.16,
 'pressure': 1010,
 'humidity': 45,
 'sea_level': 1010,
 'grnd_level': 1004}

In [28]:
new["weather"][0]["icon"]

'50d'

In [27]:
new["main"]["humidity"]

45

In [29]:
new["name"]

'Ahmedabad'

In [35]:
import requests

lat = 23.033863
lon = 72.585022

API_key = "13041aa49ecf4721a622bb9380221192"

url = f"https://pro.openweathermap.org/data/2.5/forecast/hourly?lat={lat}&lon={lon}&appid={API_key}"

data = requests.get(url)

data.status_code

401

In [36]:
new1 = data.json()

In [37]:
new1

{'cod': 401,
 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}

In [62]:
lat = 23.02579
lon = 72.58727

API_key = "afc717f99a9037f35ac78572f44a98f6"
 
url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}"

response = requests.get(url)
new = response.json()
new = json.dumps(new,indent=5)

In [64]:
print(new)

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779429600,
               "main": {
                    "temp": 307.16,
                    "feels_like": 307.01,
                    "temp_min": 307.16,
                    "temp_max": 311.63,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 33,
                    "temp_kf": -4.47
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.05,
                    "deg": 275,
                    "gust": 4.95
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-22 06:00:00"
          },
          {
               "dt": 1779440400,
               "main": {
                    "temp": 309.79,
                    "feels_like": 309.54,
                    "temp_min": 309.79,
                    "temp_max": 315.06,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1000,
                    "humidity": 27,
                    "temp_kf": -5.27
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.72,
                    "deg": 269,
                    "gust": 5.66
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-22 09:00:00"
          },
          {
               "dt": 1779451200,
               "main": {
                    "temp": 312.33,
                    "feels_like": 311.66,
                    "temp_min": 312.33,
                    "temp_max": 314.91,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 998,
                    "humidity": 21,
                    "temp_kf": -2.58
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.38,
                    "deg": 286,
                    "gust": 5.92
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-22 12:00:00"
          },
          {
               "dt": 1779462000,
               "main": {
                    "temp": 309.49,
                    "feels_like": 309.34,
                    "temp_min": 309.49,
                    "temp_max": 309.49,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 28,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.77,
                    "deg": 216,
                    "gust": 7.19
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 15:00:00"
          },
          {
               "dt": 1779472800,
               "main": {
                    "temp": 305.41,
                    "feels_like": 308.78,
                    "temp_min": 305.41,
                    "temp_max": 305.41,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 53,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 2.07,
                    "deg": 215,
                    "gust": 2.93
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 18:00:00"
          },
          {
               "dt": 1779483600,
               "main": {
                    "temp": 304.2,
                    "feels_like": 305.28,
                    "temp_min": 304.2,
                    "temp_max": 304.2,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 47,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.28,
                    "deg": 274,
                    "gust": 8.81
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 21:00:00"
          },
          {
               "dt": 1779494400,
               "main": {
                    "temp": 302.48,
                    "feels_like": 304.75,
                    "temp_min": 302.48,
                    "temp_max": 302.48,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 60,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 4.33,
                    "deg": 282,
                    "gust": 8.08
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 00:00:00"
          },
          {
               "dt": 1779505200,
               "main": {
                    "temp": 304.89,
                    "feels_like": 306.6,
                    "temp_min": 304.89,
                    "temp_max": 304.89,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 1004,
                    "humidity": 48,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.1,
                    "deg": 276,
                    "gust": 6.39
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 03:00:00"
          },
          {
               "dt": 1779516000,
               "main": {
                    "temp": 311.47,
                    "feels_like": 311.25,
                    "temp_min": 311.47,
                    "temp_max": 311.47,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 24,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 11
               },
               "wind": {
                    "speed": 4.97,
                    "deg": 258,
                    "gust": 6.05
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 06:00:00"
          },
          {
               "dt": 1779526800,
               "main": {
                    "temp": 315.29,
                    "feels_like": 313.8,
                    "temp_min": 315.29,
                    "temp_max": 315.29,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04d"
                    }
               ],
               "clouds": {
                    "all": 93
               },
               "wind": {
                    "speed": 5.84,
                    "deg": 258,
                    "gust": 6.52
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 09:00:00"
          },
          {
               "dt": 1779537600,
               "main": {
                    "temp": 314.84,
                    "feels_like": 313.55,
                    "temp_min": 314.84,
                    "temp_max": 314.84,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 803,
                         "main": "Clouds",
                         "description": "broken clouds",
                         "icon": "04d"
                    }
               ],
               "clouds": {
                    "all": 56
               },
               "wind": {
                    "speed": 6.86,
                    "deg": 304,
                    "gust": 6.31
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 12:00:00"
          },
          {
               "dt": 1779548400,
               "main": {
                    "temp": 309.76,
                    "feels_like": 308.42,
                    "temp_min": 309.76,
                    "temp_max": 309.76,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 22,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 92
               },
               "wind": {
                    "speed": 2.88,
                    "deg": 266,
                    "gust": 6.01
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 15:00:00"
          },
          {
               "dt": 1779559200,
               "main": {
                    "temp": 305.93,
                    "feels_like": 306.59,
                    "temp_min": 305.93,
                    "temp_max": 305.93,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 40,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 97
               },
               "wind": {
                    "speed": 4.46,
                    "deg": 261,
                    "gust": 8.57
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 18:00:00"
          },
          {
               "dt": 1779570000,
               "main": {
                    "temp": 303.16,
                    "feels_like": 304.37,
                    "temp_min": 303.16,
                    "temp_max": 303.16,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 51,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03n"
                    }
               ],
               "clouds": {
                    "all": 39
               },
               "wind": {
                    "speed": 5.54,
                    "deg": 254,
                    "gust": 10.17
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 21:00:00"
          },
          {
               "dt": 1779580800,
               "main": {
                    "temp": 301.61,
                    "feels_like": 303.84,
                    "temp_min": 301.61,
                    "temp_max": 301.61,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 64,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 19
               },
               "wind": {
                    "speed": 4.48,
                    "deg": 284,
                    "gust": 8.76
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 00:00:00"
          },
          {
               "dt": 1779591600,
               "main": {
                    "temp": 304.22,
                    "feels_like": 306.51,
                    "temp_min": 304.22,
                    "temp_max": 304.22,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 53,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 3
               },
               "wind": {
                    "speed": 5.75,
                    "deg": 270,
                    "gust": 7.71
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 03:00:00"
          },
          {
               "dt": 1779602400,
               "main": {
                    "temp": 311.25,
                    "feels_like": 311.49,
                    "temp_min": 311.25,
                    "temp_max": 311.25,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 26,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 5
               },
               "wind": {
                    "speed": 5.95,
                    "deg": 259,
                    "gust": 7.42
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 06:00:00"
          },
          {
               "dt": 1779613200,
               "main": {
                    "temp": 315.86,
                    "feels_like": 314.91,
                    "temp_min": 315.86,
                    "temp_max": 315.86,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 6.4,
                    "deg": 263,
                    "gust": 6.83
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 09:00:00"
          },
          {

In [60]:
date = []
temp = []
speed = []
date1 = []
des = []
for i in new["list"]:
    date.append(i["dt_txt"].split(" ")[0])
    date1.append(i["dt_txt"].split(" ")[1])
    temp.append(i["main"]["temp"])
    speed.append(i["wind"]["speed"])
    des.append(i["weather"][0]["description"])

In [57]:
import pandas as pd

In [61]:
data = {"Date":date,"Time":date1,"Temp":temp,"Wind Speed":speed,"Description":des}
df = pd.DataFrame(data)
df

          Date      Time    Temp  Wind Speed       Description
0   2026-05-22  06:00:00  307.32        4.05         clear sky
1   2026-05-22  09:00:00  311.76        4.72         clear sky
2   2026-05-22  12:00:00  314.91        5.38         clear sky
3   2026-05-22  15:00:00  309.49        4.77         clear sky
4   2026-05-22  18:00:00  305.41        2.07         clear sky
5   2026-05-22  21:00:00  304.20        5.28         clear sky
6   2026-05-23  00:00:00  302.48        4.33         clear sky
7   2026-05-23  03:00:00  304.89        5.10         clear sky
8   2026-05-23  06:00:00  311.47        4.97        few clouds
9   2026-05-23  09:00:00  315.29        5.84   overcast clouds
10  2026-05-23  12:00:00  314.84        6.86     broken clouds
11  2026-05-23  15:00:00  309.76        2.88   overcast clouds
12  2026-05-23  18:00:00  305.93        4.46   overcast clouds
13  2026-05-23  21:00:00  303.16        5.54  scattered clouds
14  2026-05-24  00:00:00  301.61        4.48        few clouds
15  2026-05-24  03:00:00  304.22        5.75         clear sky
16  2026-05-24  06:00:00  311.25        5.95         clear sky
17  2026-05-24  09:00:00  315.86        6.40         clear sky
18  2026-05-24  12:00:00  315.40        7.23         clear sky
19  2026-05-24  15:00:00  309.56        4.91         clear sky
20  2026-05-24  18:00:00  305.18        3.28         clear sky
21  2026-05-24  21:00:00  302.72        5.04         clear sky
22  2026-05-25  00:00:00  301.27        4.66         clear sky
23  2026-05-25  03:00:00  304.36        5.40         clear sky
24  2026-05-25  06:00:00  311.94        5.61         clear sky
25  2026-05-25  09:00:00  316.82        6.35         clear sky
26  2026-05-25  12:00:00  315.54        8.71         clear sky
27  2026-05-25  15:00:00  309.39        4.66         clear sky
28  2026-05-25  18:00:00  305.32        3.39         clear sky
29  2026-05-25  21:00:00  302.63        3.97         clear sky
30  2026-05-26  00:00:00  301.99        3.98         clear sky
31  2026-05-26  03:00:00  304.83        5.10         clear sky
32  2026-05-26  06:00:00  311.74        5.86         clear sky
33  2026-05-26  09:00:00  316.39        6.48         clear sky
34  2026-05-26  12:00:00  315.96        6.66         clear sky
35  2026-05-26  15:00:00  307.31        4.05         clear sky
36  2026-05-26  18:00:00  304.81        4.60         clear sky
37  2026-05-26  21:00:00  303.21        4.39         clear sky
38  2026-05-27  00:00:00  301.79        3.97         clear sky
39  2026-05-27  03:00:00  304.35        5.19         clear sky